# Generated by Django 6.0.1 on 2026-01-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historiaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tipo_terapia',
            field=models.CharField(blank=True, choices=[('pediatria', 'Pediatría'), ('traumatologia', 'Traumatología'), ('neurologia', 'Neurología'), ('geriatria', 'Geriatría'), ('deportiva', 'Deportiva')], max_length=20, null=True),
        ),
    ]
