# Generated by Django 6.0.1 on 2026-01-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historiaclinica_tipo_terapia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=20, null=True),
        ),
    ]
