# Generated by Django 6.0.1 on 2026-01-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historiaclinica_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
    ]
