# Generated by Django 6.0.1 on 2026-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historiaclinica_diabetes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diabetes',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
