# Generated by Django 6.0.1 on 2026-01-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_historiaclinica_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tipo_servicio',
            field=models.CharField(blank=True, choices=[('DOMICILIO', 'DOMICILIO'), ('CONSULTORIO', 'CONSULTORIO')], max_length=20, null=True),
        ),
    ]
