# Generated by Django 6.0.1 on 2026-01-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historiaclinica_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente_cama',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
