# Generated by Django 6.0.1 on 2026-01-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historiaclinica_paciente_silla'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='bipedestacion',
            field=models.CharField(blank=True, choices=[('SI CON APOYO', 'SI CON APOYO'), ('SI SIN APOYO', 'SI SIN APOYO'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
