# Generated by Django 6.0.1 on 2026-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historiaclinica_bipedestacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='control',
            field=models.CharField(blank=True, choices=[('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
