# Generated by Django 6.0.1 on 2026-01-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historiaclinica_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='trofismo',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('HIPOTROFISMO', 'HIPOTROFISMO'), ('HIPERTROFISMO', 'HIPERTROFISMO')], max_length=20, null=True),
        ),
    ]
