# Generated by Django 6.0.1 on 2026-01-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historiaclinica_trofismo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='marcha',
            field=models.CharField(blank=True, choices=[('INDEPENDIENTE', 'INDEPENDIENTE'), ('MULETA', 'MULETA'), ('ANDADOR', 'ANDADOR'), ('BASTON', 'BASTON'), ('OTRO', 'OTRO'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
