# Generated by Django 6.0.1 on 2026-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historiaclinica_marcha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='sensibilidad',
            field=models.CharField(blank=True, choices=[('PRESENTE', 'PRESENTE'), ('AUSENTE', 'AUSENTE')], max_length=20, null=True),
        ),
    ]
