# Generated by Django 6.0.1 on 2026-01-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historiaclinica_sensibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tono_muscular',
            field=models.CharField(blank=True, choices=[('NORMOTONO', 'NORMOTONO'), ('HIPERTONICO', 'HIPERTONICO'), ('HIPOTONICO', 'HIPOTONICO')], max_length=20, null=True),
        ),
    ]
