# Generated by Django 6.0.1 on 2026-01-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historiaclinica_tono_muscular'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='ama',
            field=models.CharField(blank=True, choices=[('CODO', 'CODO'), ('RODILLA', 'RODILLA'), ('HOMBRO', 'HOMBRO'), ('TOBILLO', 'TOBILLO'), ('CADERA', 'CADERA'), ('MUÑECA', 'MUÑECA'), ('METACARPO FALANGICAS', 'METACARPO FALANGICAS'), ('FALANGE MEDIA', 'FALANGE MEDIA'), ('FALANGE DISTAL', 'FALANGE DISTAL'), ('MATATARSOFALANGICAS', 'MATATARSOFALANGICAS'), ('CERVICAL', 'CERVICAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='marcha',
            field=models.CharField(blank=True, choices=[('INDEPENDIENTE', 'INDEPENDIENTE'), ('MULETA', 'MULETA'), ('ANDADOR', 'ANDADOR'), ('BASTÓN', 'BASTÓN'), ('OTRO', 'OTRO'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tono_muscular',
            field=models.CharField(blank=True, choices=[('NORMOTONO', 'NORMOTONO'), ('HIPERTÓNICO', 'HIPERTÓNICO'), ('HIPOTÓNICO', 'HIPOTÓNICO')], max_length=20, null=True),
        ),
    ]
