# Generated by Django 6.0.1 on 2026-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_historiaclinica_ama_alter_historiaclinica_marcha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='fuerza_muscular',
            field=models.CharField(blank=True, choices=[('UNO', 'UNO'), ('DOS', 'DOS'), ('TRES', 'TRES'), ('CUATRO', 'CUATRO'), ('CINCO', 'CINCO')], max_length=20, null=True),
        ),
    ]
