# Generated by Django 6.0.1 on 2026-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historiaclinica_fuerza_muscular'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='reflejo',
            field=models.CharField(blank=True, choices=[('AUSENTE', 'AUSENTE'), ('PRESENTE', 'PRESENTE')], max_length=20, null=True),
        ),
    ]
