# Generated by Django 6.0.1 on 2026-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historiaclinica_reflejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='ef',
            field=models.CharField(blank=True, choices=[('ESPASTICIDAD', 'ESPASTICIDAD'), ('FLACIDEZ', 'FLACIDEZ')], max_length=20, null=True),
        ),
    ]
