# Generated by Django 6.0.1 on 2026-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_historiaclinica_ef'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='paresia',
            field=models.CharField(blank=True, choices=[('CUADRIPERESIA', 'CUADRIPERESIA'), ('TETRAPARESIA', 'TETRAPARESIA'), ('HEMIPARESIA', 'HEMIPARESIA'), ('MONOPARESIA', 'MONOPARESIA'), ('PARAPARESIA', 'PARAPARESIA'), ('TRIPARESIA', 'TRIPARESIA'), ('DIPARESIA', 'DIPARESIA'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='plejia',
            field=models.CharField(blank=True, choices=[('CUADRIPLEJIA', 'CUADRIPLEJIA'), ('TETRAPLEJIA', 'TETRAPLEJIA'), ('MONOPLEJIA', 'MONOPLEJIA'), ('HOMOPLEJIA', 'HOMOPLEJIA'), ('PARAPLEJIA', 'PARAPLEJIA'), ('TRIPLEJIA', 'TRIPLEJIA'), ('DIPLEJIA', 'DIPLEJIA'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
