# Generated by Django 6.0.1 on 2026-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_historiaclinica_paresia_historiaclinica_plejia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='presion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='signos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
