# Generated by Django 6.0.1 on 2026-01-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historiaclinica_presion_historiaclinica_signos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='sintomas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
