# Generated by Django 6.0.1 on 2026-01-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_historiaclinica_af_historiaclinica_alergias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='tf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
