# Generated by Django 6.0.1 on 2026-01-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_historiaclinica_tf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='fm',
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='peso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='presion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='saturacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
