# Generated by Django 6.0.1 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_historiaclinica_fm_alter_historiaclinica_fc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='profecional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
