# Generated by Django 6.0.1 on 2026-01-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_historiaclinica_profecional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiaclinica',
            old_name='profecional',
            new_name='profesional',
        ),
    ]
