# Generated by Django 6.0.1 on 2026-01-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_profecional_historiaclinica_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='profesional',
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
    ]
