# Generated by Django 6.0.1 on 2026-01-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_historiaclinica_profesional_tratamiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tratamiento',
        ),
    ]
