# Generated by Django 6.0.1 on 2026-01-22 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('numero_sesion', models.PositiveIntegerField()),
                ('eva_inicial', models.CharField(blank=True, max_length=10)),
                ('eva_final', models.CharField(blank=True, max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('chc', models.BooleanField(default=False)),
                ('chf', models.BooleanField(default=False)),
                ('us', models.BooleanField(default=False)),
                ('infrarrojo', models.BooleanField(default=False)),
                ('magneto', models.BooleanField(default=False)),
                ('electrodos', models.BooleanField(default=False)),
                ('laser', models.BooleanField(default=False)),
                ('onda_choque', models.BooleanField(default=False)),
                ('puncion_seca', models.BooleanField(default=False)),
                ('terapia_manual', models.BooleanField(default=False)),
                ('firma_tm', models.CharField(blank=True, max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='core.paciente')),
            ],
        ),
    ]
