# Generated by Django 6.0.1 on 2026-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='fase3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='firma_tm',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
