# Generated by Django 6.0.1 on 2026-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_tratamiento_fase3_alter_tratamiento_firma_tm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='fase4',
            field=models.TextField(blank=True),
        ),
    ]
