# Generated by Django 6.0.1 on 2026-02-18 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_historiaclinica_id_alter_paciente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabilidad',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contabilidad',
            name='tipo',
            field=models.CharField(choices=[('deuda', 'Deuda (Terapia)'), ('pago', 'Pago'), ('anticipo', 'Pago Anticipado')], max_length=15),
        ),
    ]
